services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=cpadb
      - MYSQL_USER=cpauser
      - MYSQL_PASSWORD=cpapassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  chroma:
    image: chromadb/chroma:latest
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"]
      - ALLOW_RESET=false
      - ANONYMIZED_TELEMETRY=false
      - PERSIST_DIRECTORY=/data
      - CHROMA_DB_IMPL=duckdb+parquet
    volumes:
      - chroma_data:/data
    ports:
      - "8030:8000"
      - "8100:8100"
    networks:
      - app_network

  web:
    build: 
      context: ../web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../web:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - WEB_PORT=8080
    networks:
      - app_network

  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../api:/api
      - ../databases:/api/databases
      - ../logs:/api/logs
    environment:
      - API_ENV=development
    networks:
      - app_network

  streamlit:
    build:
      context: ..
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ..:/app
      - ../.env:/app/.env
    env_file:
      - ../.env
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - CHROMA_SERVER_HOST=chroma
      - CHROMA_SERVER_HTTP_PORT=8000
      - CHROMADB_HOST=chroma
      - CHROMADB_PORT=8030
      - CHROMA_API_IMPL=rest
      - CHROMA_SERVER_SSL_ENABLED=false
      - API_BASE_URL=http://api:8000
      - WEB_BASE_URL=http://web:8080
      - WEB_PUBLIC_URL=http://localhost:8080
    depends_on:
      - web
      - api
      - chroma
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  chroma_data:
    driver: local
  index_data:
    driver: local
